[package]
name = "zed-settings-sync"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["lsp", "xtask-lsp-install"]

[dependencies]
zed_extension_api = "0.7.0"

[lib]
path = "src/settings_sync.rs"
crate-type = ["cdylib"]

[workspace.lints]
[workspace.lints.clippy]
# yes, Cloudflare
unwrap_used = "deny"
expect_used = "deny"
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
correctness = "deny"
style = "deny"
