name: Check and Test
on:
  push:
  pull_request:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install rust
        uses: ./.github/actions/install-rust

      - name: check
        uses: ./.github/actions/check

  test:
    name: test ${{ matrix.target }}
    runs-on: ${{ matrix.runner  }}
    needs: check
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            bootstrap: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
            binary: cargo

          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
            bootstrap: |
              sudo apt-get update
              sudo apt-get -y install podman
              cargo install cross
              cargo clean
            binary: cross

          - target: x86_64-apple-darwin
            runner: macos-latest
            bootstrap: |
              arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              arch -x86_64 /usr/local/bin/brew install openssl@3
              echo "OPENSSL_DIR=$(/usr/local/bin/brew --prefix openssl@3)" >> $GITHUB_ENV
            binary: cargo
            
          - target: aarch64-apple-darwin
            runner: macos-latest
            bootstrap: echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
            binary: cargo

          - target: x86_64-pc-windows-msvc
            runner: windows-latest
            binary: cargo
            
          - target: aarch64-pc-windows-msvc
            runner: windows-11-arm64
            binary: cargo
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install rust
        uses: ./.github/actions/install-rust
        with:
          targets: "${{ matrix.target }}"

      - name: bootstrap
        if: ${{ matrix.bootstrap != '' }}
        run: ${{ matrix.bootstrap }}

      - name: test
        run: ${{ matrix.binary }} test --workspace
